2018-04-18 20:39:14：System->Int32 EndReceive(System.IAsyncResult)->远程主机强迫关闭了一个现有的连接。
2018-04-18 20:39:14：System->System.IAsyncResult BeginReceive(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags, System.Net.Sockets.SocketError ByRef, System.AsyncCallback, System.Object)->无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。
